version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    
    container_name: oracle-db
    ports:
      - "15210:1521"
    environment:
      - ORACLE_SID=${ORACLE_SID}
      - ORACLE_PDB=${ORACLE_PDB}
      - ORACLE_PWD=${ORACLE_PWD}
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: always

volumes:
  oracle-data: